### ISSUE TITLE
Just a `Thank You` Note

### ISSUE THREAD

**Issue by UsamaKarim** [abbasghasemi/flutter-border#1]
I am really happy to find out this package quite early as it was released, and it turn out a complete package with all my use cases. 

A huge thank you for making your contributions. ❤️

**Comment by abbasghasemi** [comment]
> I am really happy to find out this package quite early as it was released, and it turn out a complete package with all my use cases.
> 
> A huge thank you for making your contributions. ❤️

❤️❤️❤️
